# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('project_title', models.CharField(max_length=200)),
                ('project_descrption', models.CharField(max_length=2500)),
            ],
        ),
    ]
