# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrianWeb', '0002_auto_20200221_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.TextField(max_length=2500),
        ),
    ]
